### ISSUE TITLE
Request to describe the scope of the source in the README file(현재 소스코드의 범위 기술 요구)

### ISSUE THREAD

**Issue by dongoh1969** [mhpark-etri/Multi-Agent-Simulator#1]
Please describe the scope of the currently uploaded source code in the README file.
README 파일에 현재 업로드된 소스 코드의 범위 등을 기술해 주세요.

**Comment by tspark1077** [comment]
I have described the installation and usage instructions of the currently uploaded source code in the README file.
README 파일에 현재 업로드된 소스코드의 설치와 사용 방법을 기술 하였습니다.
